import type { SupremeGenreId, SupremeGenreProfile, SupremeGenreRuleSet } from "./types";

function rules(partial: Partial<SupremeGenreRuleSet> & Pick<SupremeGenreRuleSet, "narrative">): SupremeGenreRuleSet {
  return {
    emotional: [],
    dialogue: [],
    subtext: [],
    tension: [],
    market: [],
    reader: [],
    ...partial,
  };
}

function profile(
  id: SupremeGenreId,
  label: string,
  ruleSet: SupremeGenreRuleSet,
  weights: SupremeGenreProfile["weights"],
  pacingStyle: SupremeGenreProfile["pacingStyle"],
  preventionNotes: string[],
): SupremeGenreProfile {
  return { id, label, rules: ruleSet, weights, pacingStyle, preventionNotes };
}

export const SUPREME_GENRE_PROFILES: Record<SupremeGenreId, SupremeGenreProfile> = {
  romance: profile(
    "romance",
    "Romance Supreme",
    rules({
      narrative: ["Every scene advances desire or obstacle", "Chemistry through proximity and restraint", "No love declaration without cost"],
      emotional: ["Yearning > satisfaction until late arc", "Vulnerability in fragments, not monologues", "Jealousy and misread signals allowed"],
      dialogue: ["Subtext in what is NOT said", "Interruptions, deflection, unfinished sentences", "No therapist clarity"],
      subtext: ["Show want through gesture and avoidance", "Never name every feeling"],
      tension: ["Attraction → conflict → desire → frustration → payoff", "Never attraction → payoff same beat"],
      market: ["Hook with relational stakes in 120 words", "Chapter ends on emotional question"],
      reader: ["Reader must feel the almost", "Binge pull from unresolved pull"],
    }),
    { tensionSensitivity: 0.15, emotionalPacing: 0.12, dialogueRealism: 0.12, poeticDensityTolerance: 0.04, introspectionAmount: 0.05, subtextLevel: 0.15 },
    "longing",
    ["Delay mutual understanding", "Physical near-miss beats"],
  ),
  "dark-romance": profile(
    "dark-romance",
    "Dark Romance Supreme",
    rules({
      narrative: ["Power imbalance visible in every scene", "Consent and danger in tension, not explained"],
      emotional: ["Shame, obsession, and fear interleave", "No instant healing after harm"],
      dialogue: ["Control and defiance in subtext", "Threat and desire share the same silence"],
      subtext: ["Dangerous attraction shown through behavior", "Avoid moralizing the bond"],
      tension: ["Escalate risk before intimacy payoff", "Forbidden pull must cost something"],
      market: ["Provocative hook without explicit sermon", "End on consequence not comfort"],
      reader: ["Reader stays for forbidden tension", "Never sanitize the darkness early"],
    }),
    { tensionSensitivity: 0.16, emotionalPacing: 0.14, dialogueRealism: 0.13, poeticDensityTolerance: 0.03, introspectionAmount: 0.06, subtextLevel: 0.16 },
    "danger",
    ["No premature redemption", "Obsession must feel costly"],
  ),
  thriller: profile(
    "thriller",
    "Thriller Supreme",
    rules({
      narrative: ["Every chapter reveals and withholds", "Clock pressure or consequence visible"],
      emotional: ["Fear through action not exposition", "Paranoia in small details"],
      dialogue: ["Evasion and half-truths", "No one explains the plot aloud"],
      subtext: ["What characters avoid saying is the clue", "Silence after questions"],
      tension: ["Escalate stakes every 600 words", "No safe exhale until act break"],
      market: ["Opening hook = anomaly or threat", "End on revelation or new question"],
      reader: ["Reader must need the next chapter answer", "Confusion allowed, boredom never"],
    }),
    { tensionSensitivity: 0.14, emotionalPacing: 0.08, dialogueRealism: 0.11, poeticDensityTolerance: -0.02, introspectionAmount: -0.04, subtextLevel: 0.1 },
    "suspense",
    ["Cut reflective stalls", "Maintain mystery pressure"],
  ),
  fantasy: profile(
    "fantasy",
    "Fantasy Supreme",
    rules({
      narrative: ["World rules constrain magic and choice", "Quest promise must stay visible"],
      emotional: ["Wonder paired with cost", "Legacy and belonging as emotional engines"],
      dialogue: ["Register matches world — no modern therapy speak", "Mythic subtext in proverb and omission"],
      subtext: ["Magic shown through consequence", "Prophecy as pressure not spoiler"],
      tension: ["Setup magical debt before payoff", "Threat scales with knowledge gained"],
      market: ["Distinct world hook in opening", "Chapter ends on new rule or cost"],
      reader: ["Reader trusts consistent magic logic", "Never break established rules casually"],
    }),
    { tensionSensitivity: 0.1, emotionalPacing: 0.1, dialogueRealism: 0.08, poeticDensityTolerance: 0.08, introspectionAmount: 0.06, subtextLevel: 0.12 },
    "immersive",
    ["Honor world rules", "Foreshadow before reveal"],
  ),
  crime: profile(
    "crime",
    "Crime Supreme",
    rules({
      narrative: ["Procedure and moral gray in balance", "Evidence drives scene turns"],
      emotional: ["Guilt and complicity leak through behavior", "Violence has aftermath"],
      dialogue: ["Cops/criminals speak in codes", "Interrogation = power not exposition"],
      subtext: ["Lies visible in detail contradictions", "Alibis as character tells"],
      tension: ["Net tightens each chapter", "No culprit reveal without fair setup"],
      market: ["Crime anomaly in first page", "End on new suspect or evidence"],
      reader: ["Reader tracks clues actively", "Fair-play mystery contract"],
    }),
    { tensionSensitivity: 0.13, emotionalPacing: 0.07, dialogueRealism: 0.12, poeticDensityTolerance: -0.03, introspectionAmount: -0.02, subtextLevel: 0.11 },
    "danger",
    ["No omniscient detective speeches", "Maintain procedural credibility"],
  ),
  mystery: profile(
    "mystery",
    "Mystery Supreme",
    rules({
      narrative: ["Question posed before answer teased", "Red herrings with purpose"],
      emotional: ["Curiosity as primary engine", "Dread of wrong conclusion"],
      dialogue: ["Witnesses deflect; detectives observe", "No villain monologue early"],
      subtext: ["Objects and timing carry clues", "Emotion through what is hidden"],
      tension: ["Delay solution; stack questions", "Partial answers create new mysteries"],
      market: ["Hook = unexplained event", "Chapter ends on clue or misdirect"],
      reader: ["Reader must theorize", "Never cheat with withheld POV facts"],
    }),
    { tensionSensitivity: 0.12, emotionalPacing: 0.06, dialogueRealism: 0.11, poeticDensityTolerance: 0, introspectionAmount: 0.02, subtextLevel: 0.13 },
    "suspense",
    ["Fair clues on page", "No deus ex machina"],
  ),
  cozy: profile(
    "cozy",
    "Cozy Supreme",
    rules({
      narrative: ["Community and comfort frame danger", "Violence off-page or softened"],
      emotional: ["Warmth with gentle unease", "Friendship as anchor"],
      dialogue: ["Wit and warmth; no cruelty for shock", "Gossip as information channel"],
      subtext: ["Unease in domestic details", "Kindness masking secrets"],
      tension: ["Low gore, high curiosity", "Reveal restores order with cost"],
      market: ["Inviting setting in hook", "Satisfying puzzle closure per book arc"],
      reader: ["Reader feels safe but intrigued", "Never nihilistic tone"],
    }),
    { tensionSensitivity: 0.08, emotionalPacing: 0.09, dialogueRealism: 0.1, poeticDensityTolerance: 0.05, introspectionAmount: 0.04, subtextLevel: 0.1 },
    "clarity",
    ["Keep tone warm", "Mystery without brutality"],
  ),
  "young-adult": profile(
    "young-adult",
    "Young Adult Supreme",
    rules({
      narrative: ["Identity and agency in every arc", "Adult authority not omniscient"],
      emotional: ["Intensity without melodrama cliché", "First-time stakes feel world-sized"],
      dialogue: ["Authentic teen rhythm — not cringe slang dump", "Peer voice distinct from adults"],
      subtext: ["Shame and belonging in gesture", "Show identity struggle"],
      tension: ["Choice with consequence", "No preachy resolution"],
      market: ["Relatable hook in 2 sentences", "Chapter ends on social or identity turn"],
      reader: ["Reader sees themselves", "Hope without naivety"],
    }),
    { tensionSensitivity: 0.11, emotionalPacing: 0.11, dialogueRealism: 0.13, poeticDensityTolerance: 0.02, introspectionAmount: 0.08, subtextLevel: 0.12 },
    "immersive",
    ["Voice age-appropriate", "No condescending narrator"],
  ),
  horror: profile(
    "horror",
    "Horror Supreme",
    rules({
      narrative: ["Dread before gore", "Normal world corrodes gradually"],
      emotional: ["Fear through body and environment", "Denial then rupture"],
      dialogue: ["What people won't admit aloud", "Breakdown in short lines"],
      subtext: ["Wrongness in mundane details", "Never explain the monster early"],
      tension: ["Slow tighten then spike", "Safety illusion before strike"],
      market: ["Unsettling hook not jump-scare only", "End on presence or loss"],
      reader: ["Reader dreads turning page", "Atmosphere over exposition"],
    }),
    { tensionSensitivity: 0.14, emotionalPacing: 0.09, dialogueRealism: 0.09, poeticDensityTolerance: 0.06, introspectionAmount: 0.03, subtextLevel: 0.11 },
    "danger",
    ["Withhold full explanation", "Sensory dread over lecture"],
  ),
  "sci-fi": profile(
    "sci-fi",
    "Sci-Fi Supreme",
    rules({
      narrative: ["Tech/world rule changes human choice", "Concept shown through scene"],
      emotional: ["Alienation and wonder balanced", "Human cost of progress"],
      dialogue: ["Jargon only when character-true", "Ethics in conflict not speech"],
      subtext: ["Future anxiety in small habits", "Show system through person"],
      tension: ["Discovery raises new risk", "Solution creates new problem"],
      market: ["Concept hook in opening", "Chapter ends on implication"],
      reader: ["Reader trusts internal logic", "No magic tech without rules"],
    }),
    { tensionSensitivity: 0.1, emotionalPacing: 0.07, dialogueRealism: 0.1, poeticDensityTolerance: 0.02, introspectionAmount: 0.05, subtextLevel: 0.1 },
    "immersive",
    ["One clear rule change per beat", "Ground abstract in character"],
  ),
  "self-help": profile(
    "self-help",
    "Self Help Supreme",
    rules({
      narrative: ["Problem → mechanism → practice", "One actionable insight per section"],
      emotional: ["Empathy without toxic positivity", "Shame acknowledged then reframed"],
      dialogue: ["Reader address as coach not guru", "Questions over declarations"],
      subtext: ["Stories illustrate; don't replace method", "Show transformation in behavior"],
      tension: ["Hold discomfort before solution", "No instant cure framing"],
      market: ["Promise specific outcome in subtitle voice", "Chapter delivers one win"],
      reader: ["Reader feels capable not lectured", "Trust through specificity"],
    }),
    { tensionSensitivity: 0.04, emotionalPacing: 0.06, dialogueRealism: 0.1, poeticDensityTolerance: -0.04, introspectionAmount: 0.08, subtextLevel: 0.05 },
    "clarity",
    ["No empty motivational clichés", "Concrete exercises over slogans"],
  ),
  business: profile(
    "business",
    "Business Supreme",
    rules({
      narrative: ["Case → framework → application", "Numbers and decisions on page"],
      emotional: ["Stakes = money, team, mission", "Failure lessons without hype"],
      dialogue: ["Boardroom realism; no buzzword soup", "Conflict over strategy not personality"],
      subtext: ["Politics in what's unsaid in meetings", "Risk in what isn't measured"],
      tension: ["Decision points with tradeoffs", "No silver bullet"],
      market: ["ROI-clear hook", "Chapter ends on decision or metric shift"],
      reader: ["Reader trusts practitioner voice", "Specific beats generic"],
    }),
    { tensionSensitivity: 0.05, emotionalPacing: 0.04, dialogueRealism: 0.11, poeticDensityTolerance: -0.06, introspectionAmount: 0.02, subtextLevel: 0.04 },
    "clarity",
    ["Cut synergy clichés", "Mechanism over motivation poster"],
  ),
  default: profile(
    "default",
    "Default Supreme",
    rules({
      narrative: ["Scene goal and change every beat", "Forward motion always"],
      emotional: ["Behavior before label", "Cost to every revelation"],
      dialogue: ["Distinct voices", "Subtext over explanation"],
      subtext: ["Show through action and silence", "Cut named-emotion because clauses"],
      tension: ["Delay gratification", "No premature closure"],
      market: ["Strong opening line", "Chapter end pull"],
      reader: ["Curiosity sustained", "No boredom pockets"],
    }),
    { tensionSensitivity: 0, emotionalPacing: 0, dialogueRealism: 0, poeticDensityTolerance: 0, introspectionAmount: 0, subtextLevel: 0 },
    "neutral",
    ["Maintain voice consistency", "Prefer concrete over abstract"],
  ),
};
