import type { WritingBrainId } from "./types";

export interface WritingBrainProfile {
  id: WritingBrainId;
  label: string;
  domain: "fiction" | "nonfiction";
  tone: string;
  structureElements: string[];
  avoidPatterns: string[];
  readerExpectations: string[];
  commercialStructure: string;
  bestsellerMode: string;
}

export const WRITING_BRAINS: Record<WritingBrainId, WritingBrainProfile> = {
  "horticultural-guide-brain": {
    id: "horticultural-guide-brain",
    label: "Horticultural Practical Guide",
    domain: "nonfiction",
    tone: "Useful, authoritative, concrete. Technical but accessible.",
    structureElements: [
      "Practical problems and seasonal context",
      "Step-by-step procedures",
      "Troubleshooting and common mistakes",
      "Checklists and tool lists",
      "Real cases and visual descriptions",
      "Beginner-to-intermediate progression",
    ],
    avoidPatterns: [
      "Motivational self-help language",
      "Emotional transformation arcs",
      "Vague inspiration without actionable steps",
      "Storytelling that replaces instruction",
    ],
    readerExpectations: ["actionable knowledge", "seasonal clarity", "troubleshooting", "beginner safety"],
    commercialStructure: "Intro → tools/setup → fundamentals → seasonal guide → maintenance → problems → expert tips",
    bestsellerMode: "reference utility + seasonal urgency",
  },
  "practical-manual-brain": {
    id: "practical-manual-brain",
    label: "Practical Manual",
    domain: "nonfiction",
    tone: "Clear, procedural, trustworthy.",
    structureElements: ["Problem framing", "Prerequisites", "Step-by-step", "Warnings", "Checklists", "FAQ/troubleshooting"],
    avoidPatterns: ["Motivational fluff", "Abstract philosophy", "Unverifiable promises"],
    readerExpectations: ["precision", "repeatability", "clear hierarchy"],
    commercialStructure: "Setup → core procedures → edge cases → maintenance → reference appendix",
    bestsellerMode: "utility density + skim-friendly structure",
  },
  "self-help-brain": {
    id: "self-help-brain",
    label: "Self Help",
    domain: "nonfiction",
    tone: "Empathetic, credible, transformation-oriented.",
    structureElements: [
      "Emotional hook and relatable pain",
      "Credibility and reframing",
      "Framework or principle",
      "Relatable examples",
      "Actionable exercise",
      "Chapter payoff",
    ],
    avoidPatterns: ["Generic platitudes", "Unearned breakthroughs", "Therapist-speak without substance"],
    readerExpectations: ["emotional transformation", "relatable examples", "credibility", "chapter payoff"],
    commercialStructure: "Pain → insight → framework → practice → momentum",
    bestsellerMode: "emotional hooks + repeatable frameworks",
  },
  "productivity-brain": {
    id: "productivity-brain",
    label: "Productivity",
    domain: "nonfiction",
    tone: "Pragmatic, systemic, anti-hustle. Systems over motivation.",
    structureElements: ["Frameworks", "Systems", "Practical repetition", "Actionable momentum", "Authority building"],
    avoidPatterns: ["Vague motivation", "Hustle porn", "Tips without systems"],
    readerExpectations: ["frameworks", "systems", "measurable outcomes"],
    commercialStructure: "Problem → system → workflow → implementation → maintenance",
    bestsellerMode: "framework clarity + implementation density",
  },
  "psychology-brain": {
    id: "psychology-brain",
    label: "Psychology",
    domain: "nonfiction",
    tone: "Evidence-informed, empathetic, precise.",
    structureElements: ["Mechanism", "Research grounding", "Application", "Case illustration", "Practice"],
    avoidPatterns: ["Pop-psych oversimplification", "Unqualified clinical advice"],
    readerExpectations: ["understanding", "evidence", "practical application"],
    commercialStructure: "Concept → mechanism → application → integration",
    bestsellerMode: "insight clarity + applied exercises",
  },
  "memoir-brain": {
    id: "memoir-brain",
    label: "Memoir",
    domain: "nonfiction",
    tone: "Intimate, reflective, scene-driven.",
    structureElements: ["Scene memory", "Emotional truth", "Reflection", "Thematic thread", "Meaning-making"],
    avoidPatterns: ["Chronological diary drift", "Unearned wisdom", "Generic life lessons"],
    readerExpectations: ["authentic voice", "emotional truth", "memorable scenes"],
    commercialStructure: "Hook scene → thematic arc → crisis → reflection → resonance",
    bestsellerMode: "scene intensity + thematic cohesion",
  },
  "business-brain": {
    id: "business-brain",
    label: "Business",
    domain: "nonfiction",
    tone: "Strategic, authoritative, results-oriented.",
    structureElements: ["Market insight", "Framework", "Case study", "Implementation", "Metrics"],
    avoidPatterns: ["Buzzword soup", "Theory without application"],
    readerExpectations: ["strategy", "ROI clarity", "actionable playbooks"],
    commercialStructure: "Problem → strategy → playbook → case proof → scale",
    bestsellerMode: "authority + repeatable playbook",
  },
  "spirituality-brain": {
    id: "spirituality-brain",
    label: "Spirituality",
    domain: "nonfiction",
    tone: "Reverent, contemplative, grounded.",
    structureElements: ["Opening stillness", "Teaching", "Practice", "Reflection", "Integration"],
    avoidPatterns: ["Toxic positivity", "Dogmatic preaching", "Self-help crossover tone"],
    readerExpectations: ["inner clarity", "practice", "meaning", "respectful depth"],
    commercialStructure: "Invitation → teaching → practice → reflection → integration",
    bestsellerMode: "contemplative pacing + practice density",
  },
  "education-brain": {
    id: "education-brain",
    label: "Education",
    domain: "nonfiction",
    tone: "Pedagogical, structured, progressive.",
    structureElements: ["Learning objective", "Concept", "Example", "Exercise", "Assessment"],
    avoidPatterns: ["Unscaffolded complexity", "Missing progression"],
    readerExpectations: ["clarity", "progression", "practice"],
    commercialStructure: "Foundations → skills → application → mastery",
    bestsellerMode: "learning progression + exercise density",
  },
  "fitness-brain": {
    id: "fitness-brain",
    label: "Fitness",
    domain: "nonfiction",
    tone: "Direct, technical, motivating through competence.",
    structureElements: ["Form/technique", "Program tables", "Progression", "Recovery", "Safety"],
    avoidPatterns: ["Miracle promises", "Unsafe shortcuts"],
    readerExpectations: ["form first", "measurable progression", "safety"],
    commercialStructure: "Assessment → technique → program → progression → recovery",
    bestsellerMode: "program clarity + progression hooks",
  },
  "health-brain": {
    id: "health-brain",
    label: "Health",
    domain: "nonfiction",
    tone: "Evidence-based, sober, empathetic.",
    structureElements: ["Evidence", "Mechanism", "Protocol", "Warnings", "When to seek help"],
    avoidPatterns: ["Medical claims", "Sensational cures"],
    readerExpectations: ["evidence", "safety", "actionable protocols"],
    commercialStructure: "Science → mechanism → protocol → caution → case",
    bestsellerMode: "trust + actionable protocol",
  },
  "finance-brain": {
    id: "finance-brain",
    label: "Finance",
    domain: "nonfiction",
    tone: "Clear, conservative, numbers-forward.",
    structureElements: ["Principle", "Numbers", "Scenario", "Risk", "Action plan"],
    avoidPatterns: ["Get-rich-quick", "Unqualified investment advice"],
    readerExpectations: ["clarity", "risk awareness", "actionable plans"],
    commercialStructure: "Foundation → strategy → scenarios → risk → plan",
    bestsellerMode: "clarity + actionable scenarios",
  },
  "parenting-brain": {
    id: "parenting-brain",
    label: "Parenting",
    domain: "nonfiction",
    tone: "Warm, practical, non-judgmental.",
    structureElements: ["Situation", "Developmental context", "Strategy", "Scripts", "Troubleshooting"],
    avoidPatterns: ["Perfectionism", "Shame-based advice"],
    readerExpectations: ["practical scripts", "empathy", "age-appropriate guidance"],
    commercialStructure: "Context → principle → tactic → troubleshooting → reassurance",
    bestsellerMode: "relatable scenarios + ready scripts",
  },
  "study-guide-brain": {
    id: "study-guide-brain",
    label: "Study Guide",
    domain: "nonfiction",
    tone: "Structured, exam-oriented, efficient.",
    structureElements: ["Key concepts", "Summaries", "Practice questions", "Mnemonics", "Review"],
    avoidPatterns: ["Unstructured dumps", "Missing assessment"],
    readerExpectations: ["efficiency", "retention", "exam readiness"],
    commercialStructure: "Overview → concepts → practice → review → exam strategy",
    bestsellerMode: "retention density + practice volume",
  },
  "biography-brain": {
    id: "biography-brain",
    label: "Biography",
    domain: "nonfiction",
    tone: "Documentary, researched, narrative where appropriate.",
    structureElements: ["Timeline anchors", "Primary sources feel", "Context", "Turning points", "Legacy"],
    avoidPatterns: ["Hagiography", "Unverified claims"],
    readerExpectations: ["accuracy", "narrative momentum", "context"],
    commercialStructure: "Origin → rise → conflict → legacy",
    bestsellerMode: "turning-point pacing + contextual depth",
  },
  "cookbook-brain": {
    id: "cookbook-brain",
    label: "Cookbook",
    domain: "nonfiction",
    tone: "Sensory, precise, inviting.",
    structureElements: ["Ingredients", "Prep", "Steps", "Timing", "Variations", "Tips"],
    avoidPatterns: ["Vague measurements", "Missing timing"],
    readerExpectations: ["repeatable recipes", "clear measurements", "tips"],
    commercialStructure: "Technique → recipes → variations → index utility",
    bestsellerMode: "recipe clarity + aspirational presentation",
  },
  "technical-manual-brain": {
    id: "technical-manual-brain",
    label: "Technical Manual",
    domain: "nonfiction",
    tone: "Precise, hierarchical, reference-grade.",
    structureElements: ["Prerequisites", "Configuration", "Procedures", "Troubleshooting", "Reference tables"],
    avoidPatterns: ["Ambiguous steps", "Missing warnings"],
    readerExpectations: ["precision", "reference utility", "troubleshooting"],
    commercialStructure: "Setup → operations → troubleshooting → reference",
    bestsellerMode: "reference density + error prevention",
  },
  "romance-brain": {
    id: "romance-brain",
    label: "Romance",
    domain: "fiction",
    tone: "Emotionally charged, intimate, relationship-forward.",
    structureElements: ["Attraction beat", "Emotional obstacle", "Intimacy escalation", "Vulnerability", "Payoff"],
    avoidPatterns: ["Instant resolution", "Flat conflict", "Therapist dialogue"],
    readerExpectations: ["chemistry", "emotional payoff", "relationship arc"],
    commercialStructure: "Meet → tension → deepening → crisis → resolution",
    bestsellerMode: "emotional hooks + relationship momentum",
  },
  "dark-romance-brain": {
    id: "dark-romance-brain",
    label: "Dark Romance",
    domain: "fiction",
    tone: "Intense, forbidden, psychologically charged.",
    structureElements: [
      "Delayed emotional payoff",
      "Attraction tension",
      "Forbidden energy",
      "Micro-conflict",
      "Possessive psychology",
      "Chapter cliffhangers",
    ],
    avoidPatterns: ["Sanitized conflict", "Early full confession", "Resolution without consequence"],
    readerExpectations: ["tension", "forbidden energy", "slow burn darkness", "addictive pacing"],
    commercialStructure: "Dangerous attraction → power play → vulnerability crack → consequence → escalation",
    bestsellerMode: "BookTok intensity + cliffhanger density",
  },
  "enemies-to-lovers-brain": {
    id: "enemies-to-lovers-brain",
    label: "Enemies to Lovers",
    domain: "fiction",
    tone: "Spiky, competitive, slow thaw.",
    structureElements: ["Antagonistic chemistry", "Forced proximity", "Respect earned", "Vulnerability reveal", "Shift"],
    avoidPatterns: ["Instant forgiveness", "Flat enemies", "Unearned trust"],
    readerExpectations: ["banter", "slow thaw", "earned intimacy"],
    commercialStructure: "Clash → friction → respect → crack → surrender",
    bestsellerMode: "banter density + slow thaw payoff",
  },
  "slow-burn-brain": {
    id: "slow-burn-brain",
    label: "Slow Burn",
    domain: "fiction",
    tone: "Restrained, longing, tension through delay.",
    structureElements: ["Almost moments", "Withheld contact", "Internal longing", "Delayed payoff", "Micro-releases"],
    avoidPatterns: ["Early full payoff", "Rushed intimacy", "Tension collapse"],
    readerExpectations: ["longing", "delayed payoff", "tension maintenance"],
    commercialStructure: "Spark → restraint → escalation → denial → release",
    bestsellerMode: "almost-contact density + delayed payoff",
  },
  "fantasy-brain": {
    id: "fantasy-brain",
    label: "Fantasy",
    domain: "fiction",
    tone: "Immersive, wonder-balanced, rule-consistent.",
    structureElements: ["World rules", "Magic cost", "Quest beat", "Wonder", "Consequence"],
    avoidPatterns: ["Rule-breaking convenience", "Exposition dumps"],
    readerExpectations: ["immersion", "magic system clarity", "wonder"],
    commercialStructure: "Ordinary → call → trials → revelation → transformation",
    bestsellerMode: "wonder hooks + rule-consistent escalation",
  },
  "epic-fantasy-brain": {
    id: "epic-fantasy-brain",
    label: "Epic Fantasy",
    domain: "fiction",
    tone: "Grand scale, political, mythic.",
    structureElements: ["World scale", "Faction politics", "Prophecy/legacy", "Battle/setpiece", "Cost of power"],
    avoidPatterns: ["Scope without stakes", "Name soup"],
    readerExpectations: ["scope", "political intrigue", "mythic stakes"],
    commercialStructure: "Inciting imbalance → alliances → escalation → reckoning → new order",
    bestsellerMode: "scope revelation + faction tension",
  },
  "thriller-brain": {
    id: "thriller-brain",
    label: "Thriller",
    domain: "fiction",
    tone: "Urgent, propulsive, high stakes.",
    structureElements: ["Ticking clock", "Revelation ladder", "Setpieces", "Betrayal risk", "Cliffhangers"],
    avoidPatterns: ["Passive protagonist", "Low stakes", "Exposition stalls"],
    readerExpectations: ["pace", "stakes", "twists", "compulsion"],
    commercialStructure: "Threat → investigation → escalation → reversal → confrontation",
    bestsellerMode: "hook density + cliffhanger cadence",
  },
  "psychological-thriller-brain": {
    id: "psychological-thriller-brain",
    label: "Psychological Thriller",
    domain: "fiction",
    tone: "Unreliable, claustrophobic, mind-bending.",
    structureElements: ["Unreliable perception", "Paranoia", "Identity doubt", "Slow reveal", "Disturbing normalcy"],
    avoidPatterns: ["Obvious twists", "Flat psychology"],
    readerExpectations: ["unease", "mind games", "slow dread"],
    commercialStructure: "Normal crack → doubt → obsession → reveal → reckoning",
    bestsellerMode: "dread accumulation + perception shifts",
  },
  "crime-brain": {
    id: "crime-brain",
    label: "Crime",
    domain: "fiction",
    tone: "Gritty, procedural or noir, morally complex.",
    structureElements: ["Crime inciting", "Investigation", "Underworld logic", "Moral gray", "Consequence"],
    avoidPatterns: ["Clean morality", "Plot convenience"],
    readerExpectations: ["grit", "procedure or noir atmosphere", "consequences"],
    commercialStructure: "Crime → investigation → complication → exposure → fallout",
    bestsellerMode: "procedure clarity + moral tension",
  },
  "mafia-brain": {
    id: "mafia-brain",
    label: "Mafia Romance / Crime",
    domain: "fiction",
    tone: "Power, loyalty, danger, forbidden desire.",
    structureElements: ["Empire logic", "Loyalty tests", "Violence shadow", "Forbidden bond", "Empire cost"],
    avoidPatterns: ["Sanitized crime", "Cartoon villains"],
    readerExpectations: ["power dynamics", "loyalty", "danger", "forbidden attraction"],
    commercialStructure: "Empire → bond → betrayal risk → sacrifice → reckoning",
    bestsellerMode: "power fantasy + loyalty tension",
  },
  "mystery-brain": {
    id: "mystery-brain",
    label: "Mystery",
    domain: "fiction",
    tone: "Curious, fair-play clues, deductive.",
    structureElements: ["Crime/puzzle", "Clues", "Red herrings", "Deduction", "Reveal"],
    avoidPatterns: ["Unfair reveals", "Missing clues"],
    readerExpectations: ["fair play", "curiosity", "satisfying reveal"],
    commercialStructure: "Crime → clues → false leads → deduction → reveal",
    bestsellerMode: "clue density + curiosity loops",
  },
  "cozy-mystery-brain": {
    id: "cozy-mystery-brain",
    label: "Cozy Mystery",
    domain: "fiction",
    tone: "Warm, community-centered, low gore.",
    structureElements: ["Amateur sleuth", "Community texture", "Gentle humor", "Puzzle", "Restoration"],
    avoidPatterns: ["Graphic violence", "Bleak tone"],
    readerExpectations: ["comfort", "community", "puzzle", "low gore"],
    commercialStructure: "Disruption → investigation → community → reveal → restoration",
    bestsellerMode: "community charm + puzzle satisfaction",
  },
  "horror-brain": {
    id: "horror-brain",
    label: "Horror",
    domain: "fiction",
    tone: "Dread-forward, sensory, suggestive.",
    structureElements: ["Normal crack", "Dread build", "Suggestion over show", "Body response", "Echo ending"],
    avoidPatterns: ["Early monster reveal", "Gratuitous gore"],
    readerExpectations: ["dread", "suggestion", "visceral fear"],
    commercialStructure: "Normal → crack → escalation → partial reveal → echo",
    bestsellerMode: "dread pacing + sensory hooks",
  },
  "dystopian-brain": {
    id: "dystopian-brain",
    label: "Dystopian",
    domain: "fiction",
    tone: "Oppressive, systemic, resistance-coded.",
    structureElements: ["System rules", "Surveillance", "Small rebellion", "Cost of defiance", "Hope fracture"],
    avoidPatterns: ["Easy overthrow", "Vague systems"],
    readerExpectations: ["system clarity", "oppression", "resistance stakes"],
    commercialStructure: "Compliance → crack → rebellion → cost → reckoning",
    bestsellerMode: "system reveal + rebellion tension",
  },
  "ya-brain": {
    id: "ya-brain",
    label: "Young Adult",
    domain: "fiction",
    tone: "Identity-forward, high emotion, accessible.",
    structureElements: ["Identity quest", "Firsts", "Peer pressure", "Agency", "Coming-of-age beat"],
    avoidPatterns: ["Adult voice drift", "Condescension"],
    readerExpectations: ["identity", "emotion", "agency", "relatability"],
    commercialStructure: "Identity question → trial → failure → growth → claim",
    bestsellerMode: "identity hooks + emotional intensity",
  },
  "sci-fi-brain": {
    id: "sci-fi-brain",
    label: "Sci-Fi",
    domain: "fiction",
    tone: "Speculative, idea-driven, consequence-focused.",
    structureElements: ["Tech/speculative premise", "World logic", "Human cost", "Exploration", "Implication"],
    avoidPatterns: ["Magic tech", "Idea without human stakes"],
    readerExpectations: ["speculation", "logic", "human stakes"],
    commercialStructure: "Premise → exploration → complication → implication → resolution",
    bestsellerMode: "premise hook + consequence depth",
  },
  "paranormal-brain": {
    id: "paranormal-brain",
    label: "Paranormal",
    domain: "fiction",
    tone: "Supernatural undercurrent, romantic or dark.",
    structureElements: ["Normal world crack", "Supernatural rules", "Attraction/danger", "Reveal", "Integration"],
    avoidPatterns: ["Rule inconsistency", "Late rule invention"],
    readerExpectations: ["supernatural intrigue", "rules", "tension"],
    commercialStructure: "Normal → hint → reveal → bond/conflict → integration",
    bestsellerMode: "supernatural tease + rule reveals",
  },
  "general-narrative-brain": {
    id: "general-narrative-brain",
    label: "General Narrative",
    domain: "fiction",
    tone: "Balanced, clear, commercially readable.",
    structureElements: ["Hook", "Development", "Turn", "Escalation", "Payoff"],
    avoidPatterns: ["Generic AI polish", "Flat pacing"],
    readerExpectations: ["clarity", "momentum", "satisfying arcs"],
    commercialStructure: "Hook → development → midpoint → crisis → resolution",
    bestsellerMode: "hook strength + pacing maintenance",
  },
};

export function getWritingBrain(id: WritingBrainId): WritingBrainProfile {
  return WRITING_BRAINS[id] || WRITING_BRAINS["general-narrative-brain"];
}
