// Auto-generated by setup.sh — env-driven, no hardcoded values.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Prefer the legacy anon JWT for auth — it is fully compatible with OAuth PKCE
// token exchange. Fall back to publishable keys when anon is not configured.
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/** True when VITE_SUPABASE_* were present at build/dev time. */
export const isSupabaseConfigured = !!(SUPABASE_URL && SUPABASE_KEY);

/** Captured at module load before detectSessionInUrl can strip ?code= from the URL. */
export function captureOAuthCallbackFromUrl() {
  if (typeof window === "undefined") return { hasCallback: false, error: "", code: "" };
  const search = new URLSearchParams(window.location.search);
  const hash = new URLSearchParams(window.location.hash.replace(/^#/, ""));
  const code = search.get("code") || "";
  const error =
    search.get("error_description") ||
    search.get("error") ||
    hash.get("error_description") ||
    hash.get("error") ||
    "";
  const hasCallback =
    !!code ||
    search.has("error") ||
    search.has("error_description") ||
    hash.has("error") ||
    hash.has("error_description");
  return { hasCallback, error, code };
}

export const frozenOAuthCallback = captureOAuthCallbackFromUrl();

// Guard: strip ALL implicit-flow hash tokens BEFORE createClient runs.
// flowType:"pkce" never uses hash-fragment access_token/refresh_token.
// Any such tokens in the hash are either a stale implicit-flow redirect or
// a misconfigured provider response. Supabase's internal URL parser can
// still pick them up even with detectSessionInUrl:false and throw
// UNAUTHORIZED_INVALID_JWT_FORMAT. Strip them unconditionally.
try {
  if (typeof window !== "undefined" && window.location.hash) {
    const h = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    if (h.has("access_token") || h.has("refresh_token")) {
      window.history.replaceState(
        null,
        "",
        window.location.pathname + window.location.search
      );
    }
  }
} catch {
  // Never block client creation on a URL-parsing failure.
}

if (!isSupabaseConfigured) {
  console.warn(
    "[Scriptora] Supabase env vars missing — auth and backend features are disabled.",
  );
}

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        // PKCE OAuth callbacks (?code=) are exchanged on client bootstrap.
        // Implicit-flow hash tokens are stripped above before createClient runs.
        detectSessionInUrl: true,
        flowType: "pkce",
      },
    })
  : (createClient<Database>("https://placeholder.supabase.co", "placeholder-key", {
      auth: { persistSession: false, autoRefreshToken: false },
    }) as SupabaseClient<Database>);
