// Auto-generated by setup.sh — env-driven, no hardcoded values.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY in .env. " +
    "Copy .env.example to .env and fill in your Supabase project credentials."
  );
}

// Guard: strip ALL implicit-flow hash tokens BEFORE createClient runs.
// flowType:"pkce" never uses hash-fragment access_token/refresh_token.
// Any such tokens in the hash are either a stale implicit-flow redirect or
// a misconfigured provider response. Supabase's internal URL parser can
// still pick them up even with detectSessionInUrl:false and throw
// UNAUTHORIZED_INVALID_JWT_FORMAT. Strip them unconditionally.
try {
  if (typeof window !== "undefined" && window.location.hash) {
    const h = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    if (h.has("access_token") || h.has("refresh_token")) {
      window.history.replaceState(
        null,
        "",
        window.location.pathname + window.location.search
      );
    }
  }
} catch {
  // Never block client creation on a URL-parsing failure.
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: "pkce",
  },
});
