// Auto-generated by setup.sh — env-driven, no hardcoded values.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export function readSupabaseEnv() {
  const url = String(import.meta.env.VITE_SUPABASE_URL || "").trim();
  const key = String(
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      import.meta.env.VITE_SUPABASE_ANON_KEY ||
      "",
  ).trim();
  return { url, key };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = readSupabaseEnv();
  if (!url || !key) return false;
  if (/INSERIRE|YOUR_|REPLACE|TODO/i.test(key)) return false;
  return true;
}

let cachedClient: SupabaseClient<Database> | null = null;

export function getSupabaseClient(): SupabaseClient<Database> {
  if (cachedClient) return cachedClient;

  const { url, key } = readSupabaseEnv();
  if (!isSupabaseConfigured()) {
    throw new Error(
      "Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY in .env. " +
        "Copy .env.example to .env and fill in your Supabase project credentials.",
    );
  }

  cachedClient = createClient<Database>(url, key, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
      flowType: "pkce",
    },
  });

  return cachedClient;
}

/** Lazy proxy — importing this module never throws; first use requires valid env. */
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop) {
    const client = getSupabaseClient() as Record<string | symbol, unknown>;
    const value = client[prop];
    if (typeof value === "function") {
      return (value as (...args: unknown[]) => unknown).bind(client);
    }
    return value;
  },
});
